output "repository" {
  description = "Created repository"
  value       = github_repository.this
}

output "alias" {
  description = "Alias (used for renaming)"
  value       = local.alias
}

output "private_keys" {
  description = "Autogenerated private keys"
  value       = tls_private_key.this
  sensitive   = true
}
