name: Release
on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    secrets: inherit
    uses: github.com/vmvarela/workflows/.github/workflows/release.yaml@v0.3.0
    with:
      devcontainer: 'ghcr.io/vmvarela/terraform-github-repository:devcontainer'
